name: Update Notion Data

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  fetch:
    runs-on: ubuntu-latest
    environment: .env
    
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fetch Notion data
        run: node scripts/notion/fetchNotion.js
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/lieux.json
          git commit -m "Update lieux.json" || echo "No changes"
          git push
